; Environment Config

[ENVIRONMENT]
SERVER                      =   PRODUCTION


[ENVIRONMENT.DEVELOP]
BASE                        =
URL                         =   {{@SCHEME}}://local.pathfinder
DEBUG                       =   3

DB_PF_DNS                   =   mysql:host=localhost;port=3306;dbname=
DB_PF_NAME                  =   pathfinder
DB_PF_USER                  =   root
DB_PF_PASS                  =

DB_UNIVERSE_DNS             =   mysql:host=localhost;port=3306;dbname=
DB_UNIVERSE_NAME            =   eve_universe
DB_UNIVERSE_USER            =   root
DB_UNIVERSE_PASS            =

CCP_SSO_URL                 =   https://sisilogin.testeveonline.com
CCP_SSO_CLIENT_ID           =
CCP_SSO_SECRET_KEY          =
CCP_SSO_JWK_CLAIM           =   login.eveonline.com
CCP_SSO_DOWNTIME            =   11:00

CCP_ESI_URL                 =   https://esi.evetech.net
CCP_ESI_DATASOURCE          =   singularity
CCP_ESI_SCOPES              =   esi-location.read_online.v1,esi-location.read_location.v1,esi-location.read_ship_type.v1,esi-ui.write_waypoint.v1,esi-ui.open_window.v1,esi-universe.read_structures.v1,esi-corporations.read_corporation_membership.v1,esi-clones.read_clones.v1,esi-characters.read_corporation_roles.v1,esi-search.search_structures.v1
CCP_ESI_SCOPES_ADMIN        =

SMTP_HOST                   =   localhost
SMTP_PORT                   =   25
SMTP_SCHEME                 =   TLS
SMTP_USER                   =   pathfinder
SMTP_PASS                   =   root

SMTP_FROM                   =   pathfinder@localhost.com
SMTP_ERROR                  =   pathfinder@localhost.com


[ENVIRONMENT.PRODUCTION]
BASE                        =
URL                         =   https://cat4u.shop
DEBUG                       =   0

; Pathfinder database
DB_PF_DNS                   =   mysql:host=mariadb;port=3306;dbname=
DB_PF_NAME                  =   pathfinder
DB_PF_USER                  =   root
DB_PF_PASS                  =   rootpass

; Universe cache DB
DB_UNIVERSE_DNS             =   mysql:host=mariadb;port=3306;dbname=
DB_UNIVERSE_NAME            =   eve_universe
DB_UNIVERSE_USER            =   root
DB_UNIVERSE_PASS            =   rootpass

; CCP DB export
DB_CCP_DNS                  =   mysql:host=mariadb;port=3306;dbname=
DB_CCP_NAME                 =   eve_lifeblood_min
DB_CCP_USER                 =   root
DB_CCP_PASS                 =   rootpass

; CCP SSO
CCP_SSO_URL                 =   https://login.eveonline.com
CCP_SSO_CLIENT_ID           =   ee300cc58d3642ab83f1f49093dd67dd
CCP_SSO_SECRET_KEY          =   OxMofhXuQiE9VKjAaPO4sy6pVaUMfhkJ5uinK3tt
CCP_SSO_JWK_CLAIM           =   login.eveonline.com
CCP_SSO_DOWNTIME            =   11:00

; CCP ESI API
CCP_ESI_URL                 =   https://esi.evetech.net
CCP_ESI_DATASOURCE          =   tranquility
CCP_ESI_SCOPES              =   esi-location.read_online.v1,esi-location.read_location.v1,esi-location.read_ship_type.v1,esi-ui.write_waypoint.v1,esi-ui.open_window.v1,esi-universe.read_structures.v1,esi-corporations.read_corporation_membership.v1,esi-clones.read_clones.v1,esi-characters.read_corporation_roles.v1,esi-search.search_structures.v1
CCP_ESI_SCOPES_ADMIN        =

; SMTP (optional)
SMTP_HOST                   =   localhost
SMTP_PORT                   =   25
SMTP_SCHEME                 =   TLS
SMTP_USER                   =
SMTP_PASS                   =

SMTP_FROM                   =   registration@pathfinder-w.space
SMTP_ERROR                  =   admin@pathfinder-w.space

; TCP Socket configuration
SOCKET_HOST                 =   pathfinder-socket
SOCKET_PORT                 =   5555

; Standalone
PF_STANDALONE_SECRET        =   P7z$$v9R2mK*Lq5@XyA8!nJ1bW^4eG6&tH3uV0iC9oZ5pD2fS7gH1jK8lM4nB6v8e9f5a2b3c4d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f

